defaults:
  - dataset: ???      
  - _self_

train: false
seed: 234
use_wandb: false

ckpt_dir: ???
use_final_ckpt: false
finetune: false
run_test_metrics: false

work_dir: ???                 

transfer:
  enabled: true
  out_dir: ${work_dir}/transfer_outputs

test_batch_size: 1
test_num_workers: 0

task:
  evaluator:
    remap_classes: false
    sliding_inference_batch: 1
    eval_classes:
      - background
      - intact
      - damaged
      - destroyed
